### PR TITLE
Rspec test cases

### PR DESCRIPTION
**Pull request by sinework**
### Testing the enumerable methods with rspec test cases.
In this project, we have added 28 test cases for the custom enumerable methods we wrote on the previous project.

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for the job done so far.
Even if the tests you wrote are correctly working, there are some cases you should take in consideration

1. For `my_each`, `my_each_with_index`, `my_select` can you add test showing that they do not mutate the original array.
For example
```rb
test_array1_clone = test_array1.clone
test_array1.my_each_with_index { |num| num + 1 }
expect(test_array1).to eq(test_array1_clone)
```

2. Concerning `my_all?`, `my_any?`, `my_none?` kindly add tests checking **Numeric/Integer** in all the array, also tests concerning mutation

Kindly add those tests and submit a new code review request
Thanks

Mael FOSSO

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Abhigyan Mahanta & Sine Shiferaw** 
Great job following the changes required from the last review :muscle:  :muscle: 
Your project meets most of the requirements :clap: :clap: :clap:  
We still need to fix some details:

- [x] Add a screenshot in your README file
- [ ] Don't edit the rubocop file, use the original

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Comment by sinework** [comment]
Regarding the screenshot, we have added it to the readme file. 
The rubocop.yml file used in this project had already been approved when we did the enumerable project. Modifying it at this stage will cause it to fail an already approved project.

**Review by andresporras3423 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Abhigyan Mahanta & Sine Shiferaw** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: :muscle:
Don't forget to merge with the develop branch

Keep going like this  :clap: :clap:

Oscar Andrés Russi Porras

**Pull request merged**
